### ISSUE TITLE
Practica Pruebas Unitarias

### ISSUE THREAD

**Issue by Band-hi** [SistemasTecTlaxiaco/practica-6-de-pruebas-unitarias-remi#1]
[PRACTICA_PRUEBAS UNITARIAS.pdf](https://github.com/SistemasTecTlaxiaco/practica-6-de-pruebas-unitarias-remi/files/8847707/PRACTICA_PRUEBAS.UNITARIAS.pdf)

**Comment by Abraham890** [comment]
calificación: 20 puntos

**Comment by josealfredo79** [comment]
bien hecho y revisado...
